# Generated by Django 5.2.7 on 2025-11-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_add_fields_and_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time',
            new_name='hora',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='service',
        ),
        migrations.AddField(
            model_name='articulo',
            name='herbalife_url',
            field=models.URLField(blank=True, help_text='URL del producto en Herbalife, si existe.', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='servicio',
            field=models.CharField(default='Masaje relajante', max_length=100),
        ),
    ]
